In [1]:
import pandas as pd
import re

In [2]:
def attendance(x):
    x = x.replace('-','')
    l = list(set(re.findall('\d{13}',x)))
    return pd.DataFrame({"CNIC":l})

In [3]:
x = """
Shakir Hussain2:51 PM
42101-9276734-9
Muhammad Ayaz2:52 PM
4410242997959
Masroor3:02 PM
42201-2286846-7
taimoor qureshi3:06 PM
4240179641627
Tatheer Fatima3:07 PM
4210124609792
Dewan S Khan3:09 PM
4220105630741
Arsalan Ahmed3:12 PM
42201-6535195-7
Dewan S Khan3:12 PM
4220105630741
Bilal Uddin3:13 PM
4220122191357
Muhammad Atique Qayyum3:16 PM
4220140225236
Tariq Mehmood3:16 PM
4220104505899
Haris Chhipa3:17 PM
4210156195059
Dewan S Khan3:17 PM
import re
a=re.findall(r'\bFrom (.*) To Everyone : (\d{5,7})',x)
Haris Chhipa3:19 PM
3130399221225
Zeeshan Naqvi3:19 PM
4210151751811
Muhammad Sameer3:20 PM
42501-1025700-1
Masroor3:20 PM
42401-1880106-5
Mohsin Kanani3:20 PM
4230108335683
Hassan Ahmed3:20 PM
4220156089133
Muhammad Sameer3:20 PM
4250110257001
Waqas Zafar3:20 PM
5440004083505
Ali Naiyar3:20 PM
4210120075463
Malik Humza3:20 PM
4240105171159
HAREEM RIZVI3:20 PM
42101-3311570-4
Muhammad Ayaz3:20 PM
4410242997959
Yusra Adnan3:20 PM
4210164790696
Shakir Hussain3:20 PM
4210182767349
Yusra Adnan3:20 PM
Yusra Adnan
Zareen Fatima3:20 PM
3520269403788
zain abidi3:20 PM
4250119167549
Muhammad Atique Qayyum3:20 PM
4250104502069
Syed Sajjad Raxa3:20 PM
4220143471143
usman ahmad3:20 PM
4220113316709
Syed Kashif3:21 PM
4250144488545
Syed Ammad Waheed3:21 PM
4210113863591
Dewan S Khan3:21 PM
4220105630741
Faizan Ehtesham3:21 PM
4240114707349
Hussain Ali3:21 PM
4220117852609
Muhammad Sameer3:21 PM
4210115022744
Arsalan Risalat3:21 PM
4220124812817
Mohsin Kanani3:21 PM
4230108335683
Syed Ammad Waheed3:21 PM
4210113863591 Syed Ammad Waheed Hassani
Asima Ali3:21 PM
4420626938874
Mushyada Ali3:21 PM
4210103553847
Muhammad Sameer3:22 PM
425010257001
Zareen Fatima3:22 PM
3520269403788
Mushyada Ali3:22 PM
4210146436547 M Afnan Ali Khan
Bilal Uddin3:22 PM
4220122868467 Abdullah
Sheikh Faizan3:22 PM
42101-7490505-9
Syed Tanveer3:22 PM
4220169252467
Sheikh Faizan3:22 PM
Sheikh Faizan
Mushyada Ali3:23 PM
4210103553847
Sheikh Faizan3:23 PM
Sheikh Faizan
42101-7490505-9
Muhammad Sameer3:23 PM
4250110257001
4210115022744
myd-bnjm-grb
"""
df = attendance(x)
print(len(df))
df.head()

39

            CNIC
0  4220169252467
1  4240179641627
2  3520269403788
3  4210124609792
4  4210192767349